name: async_phase
description: A sealed class and its subclasses representing phases of an asynchronous operation.
version: 0.6.1
repository: https://github.com/kaboc/async-phase

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
