name: async_phase
description: A sealed class and its subclasses representing phases of an asynchronous operation.
version: 0.6.2
repository: https://github.com/kaboc/async-phase

environment:
  sdk: ^3.6.2

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.5
