name: async_phase_notifier
description: "A variant of ValueNotifier that helps you better manage phases of asynchronous operations."
version: 0.8.0
repository: https://github.com/kaboc/async-phase

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  async_phase: ^0.6.2
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
